#  Copyright (c) 2017-2018 Uber Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Minimal example of how to read samples from a dataset generated by `generate_hello_world_dataset.py`
using plain Python"""

import numpy as np
from petastorm import make_reader
import pdb
import matplotlib.pyplot as plt

# def python_hello_world(dataset_url='file:///home/eric/Phd_projects/gabor_color_image_segmentation/data/Berkeley_petastorm_dataset_test'):
#     with make_reader(dataset_url) as reader:
#         # Pure python
#         ii = 0
#         for ii, sample in enumerate(reader):
#             print(ii, np.string_(sample.img_id), sample.subdir, sample.ground_truth.shape[0], sample.img_shape, sample.mean_max_min_nseg)
#             rows, cols, channels = sample.img_shape
#             print(rows, cols, channels)
#
#             imag_size = sample.img_shape
#             pdb.set_trace()

def python_hello_world(dataset_url='file:///home/eric/Phd_projects/gabor_color_image_segmentation/data/BSD_features_petastorm_dataset_test'):
    with make_reader(dataset_url) as reader:
        # Pure python
        ii = 0
        for ii, sample in enumerate(reader):
            print(ii, sample.img_id.decode('UTF-8'), sample.complex_image[0].shape, sample.gabor_feature_array.shape, sample.mean_max_min_nseg)

        pdb.set_trace()



if __name__ == '__main__':
    python_hello_world()